---
title: "Contact Us"
---

## Before Class Begins on 2024-01-16

If you have a question before class begins, send it by email to Dr. Love at `thomas dot love at case dot edu`.

## Once Class Starts

If you’ve spent 15 minutes working on something and are stuck, don’t keep working on it. ASK FOR HELP. To get help in this course, you have three main options:

1. Use our Campuswire discussion board to ask (and answer) questions about the course. This is available 24 hours a day, 7 days a week. The system is highly catered to getting you help fast and efficiently from classmates, the TAs, and myself. Rather than emailing questions to the teaching staff, I encourage you to post your questions on Campuswise. Sign up for Campuswire via the email you received on 2024-01-15 at your CWRU email.

2. Attend TA office hours to get one-on-one help or share a computer problem. TA office hours are held via Zoom, and will begin on Friday 2024-01-19, and continue through Wednesday 2024-05-01 except for Spring Break (no office hours March 9-16) and April 8 (Eclipse).

The complete schedule for TA office hours follows. All times Eastern.

Date | Time(s)
:-------: | :------------------
Sundays | 7:00 PM to 8:30 PM
Mondays | 11:40 AM to 12:50 PM, 5:00 PM to 6:30 PM, 8:00 - 9:30 PM
Tuesdays | 8:00 PM to 9:30 PM
Wednesdays | 6:00 PM to 7:30 PM
Thursdays | 8:00 PM to 9:30 PM
Fridays | 11:40 AM to 12:50 PM and 7:00 PM to 8:30 PM
Saturdays | 10:30 AM to Noon

Zoom information to join these sessions will be posted to our **Shared Google Drive** before the first session on Friday 2024-01-19.

3. Email Professor Love at `Thomas dot Love at case dot edu` with any individual concerns related to the course that you do not feel comfortable asking elsewhere, or if you have any special concerns or needs that you want him to know about, or to set up an appointment with him for a Zoom meeting.

Professor Love will also hold "drop in" hours for as long as necessary after each class. Just let him know that you want to talk with him at the end of class.
